# app-config.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |  
    app:
      title: Red Hat Developer Hub
      baseUrl: https://rhdh.zapto.org
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://rhdh.zapto.org
      cors:
        origin: https://rhdh.zapto.org
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY}                  
    auth:
      providers:
        microsoft:
          development:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
            providers:
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}
            ## uncomment if using GitHub Enterprise
            # enterpriseInstanceUrl: ${GITHUB_URL}         
    signInPage: microsoft
    scaffolder:
      defaultAuthor:
        name: S.C # Defaults to `Scaffolder`
        email: suchugh@redhat.com # Defaults to `scaffolder@backstage.io`
      defaultCommitMessage: "U can't touch this" # Defaults to 'Initial commit'     
    catalog:
      locations:
        - type: file
          target: <github url to file path>
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain, Type]    
      providers:        
        microsoftGraphOrg:
          providerId:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
            user:
              expand: manager
            group:
              filter: "startswith(displayName,'team')"
            schedule:
              frequency: PT1M
              timeout: PT50M
        githubOrg:
          id: production
          githubUrl: https://github.com
          orgs: [ "redhat-apac-stp" ]
        github:
            providerId:
              organization: 'redhat-apac-stp'
              schedule:
                frequency:
                  hours: 10
                initialDelay:
                  seconds: 15
                timeout:
                  minutes: 3              
    permission:
      enabled: true 
      rbac:
        admin:
          superUsers:
            - name: user:default/sumiranchugh_outlook.com
            - name: user:default/sumiranchugh
            - name: user:default/user1_sumiranchughoutlook.onmicrosoft.com  
    enabled:
        microsoftGraphOrg: true          
    techdocs:
      publisher:
        type: 'googleGcs'
        googleGcs:
          bucketName: 'rhdh-bucket'
    kubernetes:
      serviceLocatorMethod:
        type: 'singleTenant'
      clusterLocatorMethods:  
        - type: 'gke'
          projectId: 'openenv-b4g6h'
          exposeDashboard: true # optional
          matchingResourceLabels: # optional
            - key: 'environment'
              value: 'sandbox'                                                        
