kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secret
stringData:
  BACKEND_SECRET: OoWHHl19qEBHLy2k38n4tFCQtu0zZ3EA
  AZURE_CLIENT_ID: 64f0ddee-fb86-49d6-bd7c-d1b1a78b7eef
  AZURE_CLIENT_SECRET: itz8Q~Z~t0wFfZKqv.DA8YnAj0uEMLmDMrxLnbOX
  AZURE_TENANT_ID: ca5c237e-de91-43f8-b6e8-754144a04a80
type: Opaque