global:
  imagePullSecrets:
    - rhdh-pull-secret
  host: <dns>
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:    
    - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
      disabled: false                            
route:
  enabled: false
upstream:
  serviceAccount: 
    name: 'devhub-sa'
    create: true
    annotations:
      iam.gke.io/gcp-service-account: '<gsa>@<project_id>.iam.gserviceaccount.com'   
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: gce
      networking.gke.io/managed-certificates: "rhdh-cert"
  postgresql:
    enabled: false
  backstage:                      
    appConfig:
      backend: 
        database:
          client: pg
          # ensureExists: false
          # pluginDivisionMode: 'schema'
          # knexConfig:
          #   searchPath: ['knex', 'public']
          connection:
            host: '127.0.0.1'
            port: '5432'
            user: ${DB_USER}
            password: ${DB_PASSWORD}
          prefix: backstage_demo_ 
      auth:
        environment: development
        providers:
          guest:
            dangerouslyAllowOutsideDevelopment: true
      techdocs:
        publisher:
          type: 'googleGcs'
          googleGcs:
            bucketName: 'rhdh-bucket'
    extraEnvVarsSecrets:
      - rhdh-secret
    extraEnvVars:
      - name: POSTGRESQL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgres-password
            name: rhdh-secret
      - name: BACKEND_SECRET
        valueFrom:
          secretKeyRef:
            key: backend-secret
            name: rhdh-auth                               
    resources:
      requests:
        cpu: "2"
        memory: 4Gi  
    extraContainers:
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy
        args:
          - "--structured-logs"
          - "--port=5432"
          - "<instance>"
          - "--private-ip"
        securityContext:
          runAsNonRoot: true
