global:
  imagePullSecrets:
    - rhdh-pull-secret
  host: rhdh.zapto.org
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false        
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false  
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
        disabled: false 
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-msgraph-dynamic
        disabled: false
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic    

          
                    
route:
  enabled: false
upstream:
  service:
    loadBalancerIP: 34.102.195.189
    type: LoadBalancer
    annotations: 
      cloud.google.com/neg: '{"exposed_ports": {"7007":{"name": "neg"}}}'
  serviceAccount: 
    name: devhub-sa
    create: true
    annotations:
      iam.gke.io/gcp-service-account: rhdh-gsa@openenv-b4g6h.iam.gserviceaccount.com
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: gce
      networking.gke.io/managed-certificates: "rhdh-cert"
    # tls:
    #   enabled: true
    #   secretName: tls-certs-secret  
  backstage:      
    image:
      pullSecrets:
      - rhdh-pull-secret
      registry: quay.io #optional
      repository: rhdh/rhdh-hub-rhel9 #optional
      tag: "1.3" #optional
    podSecurityContext:
      # you can assign any random value as fsGroup
      fsGroup: 2000    
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config-rhdh.yaml 
    extraEnvVarsSecrets:
      - rhdh-secret        
    extraEnvVars:
      - name: LOG_LEVEL
        value: debug
      - name: TZ
        value: "Australia/Melbourne"  
      - name: POSTGRESQL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgres-password
            name: rhdh-postgresql   