# app-config.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |  
    app:
      title: Sandbox
      baseUrl: https://rhdh.zapto.org
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://rhdh.zapto.org
      cors:
        origin: https://rhdh.zapto.org
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY}                  
    auth:
      environment: development
      providers:
        microsoft:
          development:
            # target: https://rhdh.zapto.org:7007/api/proxy/graph 
            # authority: https://rhdh.zapto.org:7007/api/proxy/msonline 
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}
            ## uncomment if using GitHub Enterprise
            # enterpriseInstanceUrl: ${GITHUB_URL} 
        guest:
            userEntityRef: user:default/guest
            development: {}
            dangerouslyAllowOutsideDevelopment: true          
    signInPage: microsoft
    scaffolder:
      defaultAuthor:
        name: S.C # Defaults to `Scaffolder`
        email: suchugh@redhat.com # Defaults to `scaffolder@backstage.io`
      defaultCommitMessage: "U can't touch this" # Defaults to 'Initial commit'     
    catalog:
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain, Type]    
      providers:        
        microsoftGraphOrg:
          providerId:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
            user:
              expand: manager
            group:
              filter: "startswith(displayName,'team')"
            schedule:
              frequency: PT1M
              timeout: PT50M
        githubOrg:
          id: production
          githubUrl: https://github.com
          orgs: [ "sumiran-default" ]
        github:
            providerId:
              organization: 'sumiran-default'
              schedule:
                frequency:
                  hours: 10
                initialDelay:
                  seconds: 15
                timeout:
                  minutes: 3              
    permission:
      enabled: true 
      rbac:
        policyFileReload: true
        policies-csv-file: /opt/app-root/src/rbac-policy.csv
        conditionalPoliciesFile: /some/path/conditional-policies.yaml
        admin:
          superUsers:
            - name: user:default/sumiranchugh_outlook.com
            - name: user:default/sumiranchugh
            - name: user:default/user1_sumiranchughoutlook.onmicrosoft.com
            - name: group:default/teamb
            - name: user:default/user5_sumiranchughoutlook.onmicrosoft.com
            - name: user:default/abc_gmail.com 
    enabled:
        microsoftGraphOrg: true          
    techdocs:
      publisher:
        type: 'googleGcs'
        googleGcs:
          bucketName: 'devhub-bucket'
    kubernetes:
      serviceLocatorMethod:
        type: 'singleTenant'
      clusterLocatorMethods:  
        - type: 'gke'
          projectId: 'openenv-b4g6h'
          exposeDashboard: true 
    argocd:
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: argoInstance1
              url: https://proxy-rhdh.zapto.org
              username: ${ARGOCD_USERNAME}
              password: ${ARGOCD_PASSWORD}          
    proxy:
      endpoints:
        '/developer-hub':
          target: https://raw.githubusercontent.com/
          pathRewrite:
            '^/api/proxy/developer-hub': /sumiranchugh/rhdh-gke-poc/refs/heads/main/iteration-4/manifests/data.json
          changeOrigin: true
          secure: false    
        # '/msonline':
        # target: https://10.0.0.9
        # credentials: forward
        # changeOrigin: false
        # headers:
        #   host: https://login.microsoftonline.com
        #   #   Authorization: fbf92892853a844f58e43eb02b8a5f1ddfc702af
        # '/graph':
        # target: https://10.0.0.9
        # credentials: forward
        # changeOrigin: false
        # headers:
        #   host: https://graph.microsoft.com
        # #   Authorization: fbf92892853a844f58e43eb02b8a5f1ddfc702af        

