# app-config.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |  
    app:
      title: Sandbox
      baseUrl: https://rhdh.zapto.org
      cors:
        origin: https://rhdh.zapto.org                 
    auth:
      environment: production
      providers:
        microsoft:
          production:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID} 
    signInPage: microsoft
    scaffolder:
      defaultAuthor:
        name: S.C # Defaults to `Scaffolder`
        email: suchugh@redhat.com # Defaults to `scaffolder@backstage.io`
      defaultCommitMessage: "U can't touch this" # Defaults to 'Initial commit'     
    catalog:
      providers:        
        microsoftGraphOrg:
          providerId:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
            # user:
            #   filter: accountEnabled eq true and userType eq 'member'
            userGroupMember:
              search: '"displayName:team a" OR "displayName:teamb"'
              # filter: 'startswith(displayName,''team a'') or startswith(displayName,''teamb'')'
            schedule:
              frequency: PT1M
              timeout: PT50M                          
    permission:
      enabled: true 
      rbac:
        policyFileReload: true
        policies-csv-file: /opt/app-root/src/rbac-policy.csv
        conditionalPoliciesFile: /opt/app-root/src/conditional-policy.yaml
        admin:
          superUsers:
            - name: user:default/sumiranchugh_outlook.com
            - name: user:default/sumiranchugh
            - name: user:default/user1_sumiranchughoutlook.onmicrosoft.com
            - name: group:default/teamb
            - name: user:default/user5_sumiranchughoutlook.onmicrosoft.com
            - name: user:default/abc_gmail.com 
    enabled:
      microsoftGraphOrg: true
      permission: false
      kubernetes: true
      techdocs: true
    techdocs:
      #builder: external
      publisher:
        type: 'googleGcs'
        googleGcs:
          bucketName: 'rhdh-bucket'     
    proxy:
      endpoints:
        '/developer-hub':
          target: https://raw.githubusercontent.com/
          pathRewrite:
            '^/api/proxy/developer-hub': /sumiranchugh/rhdh-gke-poc/refs/heads/main/iteration-4/manifests/data.json
          changeOrigin: true
          secure: false    
    

