kind: ConfigMap
apiVersion: v1
metadata:
  name: conditional-policy
data:
  conditional-policy.yaml: |
    { 
      "roleEntityRef": "role:default/user",
      "result": "CONDITIONAL",
      "pluginId": "catalog",
      "resourceType": "catalog-entity",
      "permissionMapping": ["read"],
      conditions: {
        "anyOf": [
          {
            "rule": "IS_ENTITY_OWNER",
            "resourceType": "catalog-entity",
            "params": {
              "claims": ["group:default/team-a"]
            }
          },
          {
            "rule": "IS_ENTITY_KIND",
            "resourceType": "catalog-entity",
            "params": {
              "kinds": ["Group"]
            }
          }
        ]
      }
    }
