kind: ConfigMap
apiVersion: v1
metadata:
  name: conditional-policy
data:
  conditional-policy.yaml: |
        ---
        result: CONDITIONAL
        roleEntityRef: 'role:default/test'
        pluginId: catalog
        permissionMapping:
        - read
        - update
        resourceType: catalog-entity

        conditions:
          rule: IS_ENTITY_OWNER
          resourceType: catalog-entity
          params:
            claims:
            - 'group:default/teama'
            - 'group:default/teamb'
