kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
data:
  rbac-policy.csv: |
    # Admin Role
    # Catalog permissions
    p, role:default/admins, catalog.entity.read, read, allow
    p, role:default/admins, catalog.entity.create, create, allow
    p, role:default/admins, catalog.entity.refresh, update, allow
    p, role:default/admins, catalog.entity.delete, delete, allow
    p, role:default/admins, catalog.location.read, read, allow
    p, role:default/admins, catalog.location.create, create, allow
    p, role:default/admins, catalog.location.delete, delete, allow
    # Scaffolder permissions
    p, role:default/admins, scaffolder.action.execute, use, allow
    p, role:default/admins, scaffolder.template.parameter.read, read, allow
    p, role:default/admins, scaffolder.template.step.read, read, allow
    p, role:default/admins, scaffolder.task.create, create, allow
    p, role:default/admins, scaffolder.task.cancel, use, allow
    p, role:default/admins, scaffolder.task.read, read, allow
    # RBAC permissions
    p, role:default/admins, policy-entity, read, allow
    p, role:default/admins, policy-entity, create, allow
    p, role:default/admins, policy-entity, update, allow
    p, role:default/admins, policy-entity, delete, allow
    # # Kubernetes permissions
    # p, role:default/admins, kubernetes.proxy, use, allow
    # # OCM permissions
    # p, role:default/admins, ocm.entity.read, read, allow
    # p, role:default/admins, ocm.cluster.read, read, allow
    # # Topology permissions
    # p, role:default/admins, topology.view.read, read, allow

    # Admin User
    # this is not needed now with the new superUser setting
    g, group:default/team_a, role:default/admins

    # team_a Role
    # Catalog permissions
    p, role:default/user, catalog.entity.read, read, allow
    p, role:default/user, catalog.entity.create, create, allow
    p, role:default/user, catalog.entity.refresh, update, allow
    p, role:default/user, catalog.entity.delete, delete, allow
    p, role:default/user, catalog.location.read, read, allow
    p, role:default/user, catalog.location.create, create, allow
    p, role:default/user, catalog.location.delete, delete, allow
    # Scaffolder permissions
    p, role:default/user, scaffolder.action.execute, use, allow
    p, role:default/user, scaffolder.template.parameter.read, read, allow
    p, role:default/user, scaffolder.template.step.read, read, allow
    p, role:default/user, scaffolder.task.create, create, allow
    p, role:default/user, scaffolder.task.cancel, use, allow
    p, role:default/user, scaffolder.task.read, read, allow
    # RBAC permissions
    p, role:default/user, policy-entity, read, allow
    # p, role:default/user, permission.policy-entity.create, create, allow
    # p, role:default/user, permission.policy-entity.update, update, allow
    # p, role:default/user, permission.policy-entity.delete, delete, allow
    # Kubernetes permissions
    #p, role:default/user, kubernetes.proxy, use, allow
    # Topology permissions
    #p, role:default/user, topology.view.read, read, allow

    # Groups
    g, group:default/teamb, role:default/user

