global:
  host: rhdh-lab.zapto.org
route:
  enabled: false
upstream: 
  service:
    ports:
      backend: 443
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations: 
      cloud.google.com/l4-rbs: "enabled"             
  backstage:
    extraEnvVars:
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: '0'
    - name: BACKEND_SECRET
      valueFrom:
        secretKeyRef:
          key: backend-secret
          name: rhdh-auth
    - name: POSTGRESQL_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgres-password
          name: rhdh-postgresql               
    livenessProbe:
      httpGet:
        scheme: HTTPS 
    readinessProbe:
      httpGet:
        scheme: HTTPS
    resources:
      requests:
        cpu: 2
        memory: 4Gi            
    appConfig:
      backend:
        https: true
      auth:
        environment: development
        providers:
          guest:
            dangerouslyAllowOutsideDevelopment: true      
    image:
      pullSecrets:
      - rhdh-pull-secret
    podSecurityContext:
      # you can assign any random value as fsGroup
      fsGroup: 2000
  postgresql:
    primary:
      podSecurityContext:
        enabled: true
        # you can assign any random value as fsGroup
        fsGroup: 3000
