global:
  host: <dns>
  imagePullSecrets:
    - rhdh-pull-secret
route:
  enabled: false
upstream: 
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: gce
      networking.gke.io/managed-certificates: "rhdh-cert" 
  backstage:
    resources:
      requests:
        cpu: 2
        memory: 4Gi            
    appConfig:
      auth:
        environment: development
        providers:
          guest:
            dangerouslyAllowOutsideDevelopment: true
    podSecurityContext:
      # you can assign any random value as fsGroup
      fsGroup: 2000
  postgresql:
    primary:
      podSecurityContext:
        enabled: true
        # you can assign any random value as fsGroup
        fsGroup: 3000
