global:
  imagePullSecrets:
    - rhdh-pull-secret
  host: rhdh.zapto.org
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false        
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false 
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        disabled: false
      # - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-argocd
      #   disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd
        disabled: false
      - package: 	./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
        disabled: false         
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
        disabled: false 
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-msgraph-dynamic
        disabled: false
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic 
      - disabled: true
        package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-github-pull-requests


          
                    
route:
  enabled: false
  
upstream:
  postgresql:
    enabled: false

  service:
    ports:
      backend: 443
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations: 
      cloud.google.com/l4-rbs: "enabled"
    #   cloud.google.com/neg: '{"exposed_ports": {"7007":{"name": "neg"}}}'
  serviceAccount: 
    name: devhub-sa
    create: true
    annotations:
      iam.gke.io/gcp-service-account: rhdh-gsa@openenv-lhwpr.iam.gserviceaccount.com                     
  backstage:
    appConfig:
      backend:
        https: true
          # certificate:
          #   key: ${BACKSTAGE_SSL_KEY} # key in pem format 
          #   cert: ${BACKSTAGE_SSL_CERT} # cert in pem format 
        database:
          client: pg
          # ensureExists: true
          # pluginDivisionMode: 'schema'
          # knexConfig:
          #   searchPath: ['knex', 'public']
          connection:
            host: '127.0.0.1'
            port: '5432'
            user: ${DB_USER}
            password: ${DB_PASSWORD}
          prefix: devhub_plugin_   
    image:
      pullPolicy: IfNotPresent
      pullSecrets:
      - rhdh-pull-secret
      registry: quay.io #optional
      repository: rhdh/rhdh-hub-rhel9 #optional
      tag: "1.3" #optional
    podSecurityContext:
      # you can assign any random value as fsGroup
      fsGroup: 2000    
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config-rhdh.yaml 
    extraEnvVarsSecrets:
      - rhdh-secret        
    extraEnvVars:
      - name: LOG_LEVEL
        value: debug
      - name: TZ
        value: "Australia/Melbourne"
      # - name: HTTPS_PROXY
      #   value: https://10.0.0.9  
      # - name: GLOBAL_AGENT_HTTP_PROXY
      #   value: http://10.0.0.9         
      # - name: GLOBAL_AGENT_NO_PROXY
      #   value: localhost
      # - name: GLOBAL_AGENT_HTTPS_PROXY
      #   value: https://10.0.0.9           
      # - name: POSTGRESQL_ADMIN_PASSWORD
      #   valueFrom:
      #     secretKeyRef:
      #       key: postgres-password
      #       name: rhdh-postgresql   
    livenessProbe:
      httpGet:
        scheme: HTTPS 
    readinessProbe:
      httpGet:
        scheme: HTTPS
    extraContainers:
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy
        args:
          - "--structured-logs"
          - "--port=5432"
          - "openenv-lhwpr:australia-southeast2:devhub"
        securityContext:
          runAsNonRoot: true
    extraVolumeMounts:
      - mountPath: /opt/app-root/src/rbac-policy.csv
        subPath: rbac-policy.csv
        name: rbac-policy
      - mountPath: /opt/app-root/src/conditional-policy.yaml
        subPath: conditional-policy.yaml
        name: conditional-policy     
      - mountPath: /opt/app-root/src/app-config-rhdh.yaml
        name: app-config-rhdh
        subPath: app-config-rhdh.yaml
      - mountPath: /opt/app-root/src/app-config-from-configmap.yaml
        name: backstage-app-config
        subPath: app-config.yaml
      - mountPath: /opt/app-root/src/dynamic-plugins-root
        name: dynamic-plugins-root
      - mountPath: /var/log/audit
        name: audit-log-data     
    extraVolumes:
      - name: rbac-policy
        configMap:
          name: rbac-policy
      - name: conditional-policy
        configMap:
          name: conditional-policy   
      - name: dynamic-plugins-root
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
      - configMap:
          defaultMode: 420
          name: dynamic-plugins
          optional: true
        name: dynamic-plugins
      - name: dynamic-plugins-npmrc
        secret:
          defaultMode: 420
          optional: true
          secretName: dynamic-plugins-npmrc             
      - name: dynamic-plugins-registry-auth
        secret:
          defaultMode: 416
          optional: true
          secretName: rhdh-dynamic-plugins-registry-auth
      - name: npmcacache
        emptyDir: {}
      - name: audit-log-data
        persistentVolumeClaim:
          claimName: rhdh-audit-log  
          

    
                        