global:
  host: <dns>
  imagePullSecrets:
    - rhdh-pull-secret
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
        disabled: false          
route:
  enabled: false
upstream:
  serviceAccount: 
    name: 'devhub-sa'
    create: true
    annotations:
      iam.gke.io/gcp-service-account: '<gsa>@<project_id>.iam.gserviceaccount.com'   
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: gce
      networking.gke.io/managed-certificates: "rhdh-cert" 
  backstage:      
    podSecurityContext:
      # you can assign any random value as fsGroup
      fsGroup: 2000
    resources:
      requests:
        cpu: 2
        memory: 4Gi
    appConfig:
      auth:
        environment: development
        providers:
          guest:
            dangerouslyAllowOutsideDevelopment: true       
  auth:
    environment: development
    providers:
      guest:
        dangerouslyAllowOutsideDevelopment: true
  techdocs:
    publisher:
      type: 'googleGcs'
      googleGcs:
        bucketName: 'rhdh-bucket'
  postgresql:
    primary:
      podSecurityContext:
        enabled: true
        # you can assign any random value as fsGroup
        fsGroup: 3000 
